ecomak/core/urls.py
from django.urls import path , include

from core.views import index , product_list_view , category_list , category_product_list_views , vendor_list_view, vendor_detail_view , product_detail_view , tag_list , ajax_add_review , search_view , filter_product , add_to_cart , cart_view

app_name='core'
urlpatterns=[
    # Homepage
    path("",index, name="index"),
    path("products/",product_list_view,name='product_list'),
    path("product/<pid>",product_detail_view,name="product_detail"),

    # Category
    path("category/",category_list,name='category_list'),
    path("category/<cid>/",category_product_list_views,name='category_product_list'),  
    
    # vendor 
    path("vendor/",vendor_list_view,name="vendor_list"),
    path("vendor/<vid>", vendor_detail_view,name="vendor_details"),

    #Tags

    path("products/tag/<tag_slug>/",tag_list , name="tags"),

    # Add reviews

    path('ajax-add-review/<pid>/', ajax_add_review,name='ajax_add_review'),

    # search

    path('search/', search_view , name="search"),

    # Filter Product URL 
    path("filter-product",filter_product ,name="filter_product" ),

    # add to cart URL
    path("add-to-cart/", add_to_cart , name="add_to_cart"),

    # cart page url 
    path("cart/", cart_view , name="cart_view"),
]

ecomak/ecomak/urls.py
from django.contrib import admin
from django.urls import path , include
from core.views import index , base
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',base,name="base"),
    path("",include("core.urls")),
    path("ckeditor/",include("ckeditor_uploader.urls")),
    path("user/",include("userauths.urls"),name="User"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomak/userauths/urls.py
from django.urls import path
from . import views
app_name = 'userauths'
urlpatterns = [
    path("sign-up/",views.register_view , name="signup"),
    path("sign-in/",views.login_view , name="login"),
    path("sign-out/",views.logout_view , name="logout"),
    
]

ecomak/templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/product.css' %}">
    <link rel="stylesheet" href="{% static 'css/category-list.css' %}">
    <link rel="stylesheet" href="{% static 'css/category-product-list.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor-list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/product-detail.css' %}">
    

   
    <title>Document</title>

</head>
<body>
    <header>
        <nav class="nav-top">
            <div>
                <ul>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">My Account</a></li>
                    <li><a href="#">Wishlist</a></li>
                    <li><a href="#">Order Tracker</a></li>
                </ul>
            </div>
            <div>
                <p>100% Secure delivery without contacting the courier</p>
                <p>Supper Value Deals- Save more with coupons</p>
                <p>Trendy 25 Silver jewelry, save up 35% off today</p>
            </div>
            <div>
                <ul>
                    <li>Need help?Call +9112345667</li>
                    <li>English</li>
                    <li>IND</li>
                </ul>
            </div>
        </nav>

        <nav class="nav-mid">
            <div class="logo">
                <img src="{% static 'assest/logo.png' %}" alt="">
            </div>

            <div class="search-bar">
                <div>
                    <h5>All Category</h5>
                    <form action="{% url 'core:search' %}" method="GET">
                        <input type="text" name="q">
                        <button type="submit">Search</button>
                    </form>
                </div>
                
            </div>
            <div>
                <div>
                    <i class="fa-solid fa-code-compare"></i>
                    <p><a href="">Compare</a></p>
                </div>
                <div>
                    <i class="fa-regular fa-heart"></i>
                    <p>Wishlist</p>
                </div>
                <div>
                    <i class="fa-solid fa-cart-shopping cart-items-count " >{{ request.session.cart_data_obj|length }}</i>
                    <p>Cart</p>
                </div>
                <div>
                    <i class="fa-regular fa-user"></i>
                    <p>Account</p>
                    {% if user.is_authenticated %}
                        <a href="{% url 'userauths:logout' %}">logout</a>
                    {% else %}
                        <a href="{% url 'userauths:login' %}">login</a>
                    {% endif %}
                </div>
            </div>
        </nav>

        <nav class="nav-bot">
            <div class="first">
                <span>Browse All Category</span>

                
            </div>

            <div class="second">
                <div>
                    <i class="fa-solid fa-fire"></i>
                    <span>Deals</span>
                </div>

                <div class="nav-item">
                    <h6>Home</h6>
                    <ul class="dropdown">
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                    </ul>  
                </div>

                <div class="nav-item">
                    <h6>About</h6>
                    
                </div>

                <div class="nav-item">
                    <h6>Category</h6>
                    <ul class="dropdown">
                        {% for c in categories %}
                            <li><a href="/category/{{c.cid}}">{{c.title}}</a></li>
                            <!-- <li><a href="#">Task1</a></li>
                            <li><a href="#">Task1</a></li>
                            <li><a href="#">Task1</a></li> -->
                        {% endfor %}
                                <hr>
                            <li><a href="/category/">View All Category</a></li>
                    </ul>  
                </div>

                <div class="nav-item">
                    <h6>Shop</h6>
                    <ul class="dropdown">
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                    </ul>  
                </div>

                <div class="nav-item">
                    <h6>Venders</h6>
                    <ul class="dropdown">
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                    </ul>  
                </div>

                <div class="nav-item">
                    <h6>Mega Menu</h6>
                    <ul class="dropdown">
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                    </ul>  
                </div>

                <div class="nav-item">
                    <h6>blog</h6>
                    <ul class="dropdown">
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                    </ul>  
                </div>

                <div class="nav-item">
                    <h6 >Pages</h6>
                    <ul class="dropdown">
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                        <li><a href="#">Task1</a></li>
                    </ul>  
                </div>

            </div>

        </nav>
       
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}}">
                    <strong>{{ message }}</strong>
                </div>
            {% endfor %}

        {% endif %}

    </header>
    

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <div class="extra" style="height: 100vh; width: 100%;"></div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{% static 'js/header.js' %}"></script>
    <script src="{% static 'js/products.js' %}"></script>
    <script src="{% static 'js/function.js' %}"></script>
</body>
</html>