ecomak/core/urls.py
from django.urls import path , include

from core.views import index , product_list_view , category_list , category_product_list_views , vendor_list_view, vendor_detail_view , product_detail_view , tag_list , ajax_add_review , search_view , filter_product , add_to_cart , cart_view

app_name='core'
urlpatterns=[
    # Homepage
    path("",index, name="index"),
    path("products/",product_list_view,name='product_list'),
    path("product/<pid>",product_detail_view,name="product_detail"),

    # Category
    path("category/",category_list,name='category_list'),
    path("category/<cid>/",category_product_list_views,name='category_product_list'),  
    
    # vendor 
    path("vendor/",vendor_list_view,name="vendor_list"),
    path("vendor/<vid>", vendor_detail_view,name="vendor_details"),

    #Tags

    path("products/tag/<tag_slug>/",tag_list , name="tags"),

    # Add reviews

    path('ajax-add-review/<pid>/', ajax_add_review,name='ajax_add_review'),

    # search

    path('search/', search_view , name="search"),

    # Filter Product URL 
    path("filter-product",filter_product ,name="filter_product" ),

    # add to cart URL
    path("add-to-cart/", add_to_cart , name="add_to_cart"),

    # cart page url 
    path("cart/", cart_view , name="cart_view"),
]

ecomak/ecomak/urls.py
from django.contrib import admin
from django.urls import path , include
from core.views import index , base
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',base,name="base"),
    path("",include("core.urls")),
    path("ckeditor/",include("ckeditor_uploader.urls")),
    path("user/",include("userauths.urls"),name="User"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomak/core/forms.py
from django import forms
from stripe import Review
from core.models import ProductReview

RATING = (
    (1,'★☆☆☆☆'),
    (2,'★★☆☆☆'),
    (3,'★★★☆☆'),
    (4,'★★★★☆'),
    (5,'★★★★★'),
)


# class ProductReviewForm(forms.ModelForm):
#     review = forms.CharField(widget=forms.Textarea(attrs={
#         'placeholder': 'Write review',
#         'name': 'review',  # Adding name attribute for the review field
#     }))
#     rating = forms.ChoiceField(choices=RATING, widget=forms.Select(attrs={
#         'name': 'rating',  # Adding name attribute for the rating field
#     }))

#     class Meta:
#         model = ProductReview
#         fields = ["review", "rating"]

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':"Write Review"}))

    class Meta: 
        model = ProductReview
        fields = ['review','rating']

        

ecomak/core/views.py
from django.shortcuts import render , get_object_or_404
from django.http import HttpResponse , JsonResponse
from core.models import Product , CartOrder , Category , Vendor ,CartOrderItems , ProductImages ,ProductReview, Wishlists ,Address
from django.db.models import Count , Avg
from taggit.models import Tag
from .forms import ProductReviewForm
from django.template.loader import render_to_string

# Create your views here.

def index(request):
    products = Product.objects.filter(product_status='published', featured="True")
    
    
    context= {
        "products":products
    }

    return render(request,'core/index.html',context)



def product_list_view(request):
    products = Product.objects.filter(product_status='published')

    context= {
        "products":products
    }

    return render(request,'core/product-list.html',context)



def category_list(request):
    categories = Category.objects.all()

    context= {
        "categories":categories
    }

    return render(request,'core/category-list.html',context)

 
def category_product_list_views(request,cid):
    category = Category.objects.get(cid=cid)
    products  = Product.objects.filter(product_status="published",category=category)
 
    context = {
        "category":category,
        "product":products
    }
    return render(request , "core/category-product-list.html",context)


def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors" : vendors,
    }

    return render(request,"core/vendor_list.html",context)


def vendor_detail_view(request, vid):
    vendor = Vendor.objects.get(vid = vid)
    products = Product.objects.filter(vendor=vendor ,product_status="published" )
    context = {
        "vendor" : vendor,
        "products" : products
    }

    return render(request,"core/vendor_detail.html",context)


def product_detail_view(request,pid):
    product = Product.objects.get(pid=pid)
    # product = get_object_or_404(Product,pid=pid)
    products = Product.objects.filter(category = product.category).exclude(pid=pid)
    p_image = product.p_image.all()

    reviews= ProductReview.objects.filter(product=product)
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))


    # Product Review form
    review_form = ProductReviewForm()

    context = {
        "product":product,
        "products":products,
        "reviews": reviews,
        "average_rating" : average_rating ,
        'review_form': review_form,
    }
    
    
    return render (request, "core/product_detail.html",context)

def tag_list(request,tag_slug=None):
    products  = Product.objects.filter(product_status="published",)
    tag = None 
    
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])
    
    context= {
        "products":products
    }

    return render(request,'core/tag.html',context)
    


def ajax_add_review(request,pid):
    
    product = Product.objects.get(pid = pid)
    user = request.user
    

    review = ProductReview.objects.create(
        user=user,
        product = product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )

    context = {
        'user': user.username,
        'review': request.POST['review'],
        "rating" : request.POST['rating'],


    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))

    return JsonResponse(
        {
            'bool':True,
            'context':context,
            'average_reviews':average_reviews,
        }

 
    )


def search_view(request):
    query = request.GET.get('q')
    products = Product.objects.filter(title__icontains=query, description__icontains=query).order_by("-date")

    context = {
        "products" :products,
        "query": query,
    }

    return  render(request,'core/search.html',context)

def filter_product(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendor[]')

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status='published').order_by("-id").distinct()
    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)


    if len(categories) >0:
        products = products.filter(category__id__in = categories).distinct()

    if len(vendors) >0:
        products = products.filter(vendor__id__in = vendors).distinct()

    
    data  = render_to_string("core/asyn/product_list.html",{"products":products})
    print(data)
    return JsonResponse({"data":data})


def add_to_cart(request):
    print("View is called")
    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        'title' : request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
        'image': request.GET['image'],
        'pid': request.GET['pid'],
    }
    print("View is called no 2")
    if 'cart_data_obj' in request.session:
        print("View is called no 3")
        if str(request.GET['id']) in request.session['cart_data_obj']:
            print("View is called no 4")
            cart_data= request.session['cart_data_obj']
            # cart_data[str(request.GET['id'])]["qty"] = int(cart_product[str(request.GET['id']['qty'])])
            cart_data[str(request.GET['id'])]["qty"] = int(request.GET['qty'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else: 
        request.session['cart_data_obj'] = cart_product
    return JsonResponse({"data":request.session['cart_data_obj'],'totalcartitem':len(request.session['cart_data_obj'])})



def cart_view(request):
    cart_total_amount = 0 
    if 'cart_data_obj'  in request.session:
        for p_id , item  in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
        return render(request, "core/cart.html")
    else : 
        return render(request, "core/cart.html")


def base(request):
    return render(request,"partials/base.html")



 

ecomak/templates/core/index.html
{% extends "partials/base.html" %}
{% load static %}

{% block content %}
    <div class="home">
        <div class="left">
            <div class="category">
                <h4>Category</h4>
                <div>
                    <ul>
                        <li>
                            <a href="#">
                                <i class="fa-solid fa-shop"></i>
                                <span>Dairy</span>
                                <span>23</span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <i class="fa-solid fa-shop"></i>
                                <span>Dairy</span>
                                <span>23</span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <i class="fa-solid fa-shop"></i>
                                <span>Dairy</span>
                                <span>23</span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <i class="fa-solid fa-shop"></i>
                                <span>Dairy</span>
                                <span>23</span>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <i class="fa-solid fa-shop"></i>
                                <span>Dairy</span>
                                <span>23</span>
                            </a>
                        </li>
                    </ul>
                </div>

            </div>

            <div class="filter">

                <div>
                    <h4>Find by price</h4>
                    <input type="range" name="" id="">
                    <div>
                        <h6>From:$500</h6>
                        <h6> To:$1000</h6>
                    </div>
                </div>

                <label for="color" class="mar">Color</label>
                <input type="checkbox"> red(56) <br>
                <input type="checkbox"> blue(45) <br>
                <input type="checkbox"> Green(3) <br>


                <label for="condition" class="mar">Item Condition</label> 
                <input type="checkbox"> new <br>
                <input type="checkbox"> refurbished <br>
                <input type="checkbox"> used <br>
                
                <div class="filter-btn">
                    Filter
                </div>

            </div>
            
            <div class="new-p">
                <h4>New Products</h4>
                <hr>
                
                <a href="#">
                    <div>
                        <div>
                            <img src="{% static 'assest/orange-juice.avif' %}" alt="">
                        </div>
                        <div>
                            <h6>Chen Cardigan</h6>
                            <p>$99.5</p>
                            <span>
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-regular fa-star"></i>
                                <i class="fa-regular fa-star"></i>
                                <i class="fa-regular fa-star"></i>
                            </span>
                        
                        </div>
                        
                    </div>
                </a>

                <a href="#">
                    <div>
                        <div>
                            <img src="{% static 'assest/orange-juice.avif' %}" alt="">
                        </div>
                        <div>
                            <h6>Chen Cardigan</h6>
                            <p>$99.5</p>
                            <span>
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-regular fa-star"></i>
                                <i class="fa-regular fa-star"></i>
                                <i class="fa-regular fa-star"></i>
                            </span>
                        
                        </div>
                        
                    </div>
                </a>

                <a href="#">
                    <div>
                        <div>
                            <img src="{% static 'assest/orange-juice.avif' %}" alt="">
                        </div>
                        <div>
                            <h6>Chen Cardigan</h6>
                            <p>$99.5</p>
                            <span>
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-regular fa-star"></i>
                                <i class="fa-regular fa-star"></i>
                                <i class="fa-regular fa-star"></i>
                            </span>
                        
                        </div>
                        
                    </div>
                </a>
                
            </div>
        
        </div>

        <div class="right">
            <div class="banner"  >
                <div>
                    <h4>Fresh Vegetable Big Discount</h4>

                    <h6>Save upto 54% off oon your first order</h6>
                    <input type="text" placeholder="Your Email address">
                    <button type="submit">Subscribe</button>
                </div>
            </div>

            <nav class="nav-home">
                <h4>Popular Products</h4>
                <div>
                    <ul>
                        <li>All</li>
                        <li>Mliks & Dairies</li>
                        <li>Coffee</li>
                        <li>Pet Food</li>
                        <li>meat</li>
                        <li>Vegetable</li>
                        <li>Furit</li>
                    </ul>
                </div>
            </nav>

            <div class="card">
                {% for product in products %}
                
                    <div class="product-card">

                        <div class="badge">-{{ product.get_percentage|floatformat }} <span> </span>%</div>
                        <div class="product-tumb">
                            <img src="{{ product.image.url }}" alt="{{ product.title }}">
                        </div>
                        <div class="product-details">
                            <span class="product-catagory">{{ product.Category }} </span>
                            <h4><a href="{% url 'core:product_detail' product.pid %}">{{ product.title }}</a></h4>
                            <p>{{ product.description }}</p>
                            <p>by {{ product.vendor.title }}</p>
                            <div class="product-bottom-details">
                                <div class="product-price"><small>{{ product.old_price }}</small > <span>$</span><span class="current-product-price-{{ product.id }}">{{ product.price }}</span></div>
                                <div class="product-links add-cart">
                                    <input  type="hidden" value="1" name="" id="product-quantity" class="product-quantity-{{ product.id }}">
                                    <input type="hidden" class="product-pid-{{ product.id }}" value="{{ product.pid }}">
                                    <input type="hidden" class="product-image-{{ product.id }}" value="{{ product.image.url }}">
                                    <input type="hidden" class="product-id-{{ product.id }}" value="{{ product.id }}">
                                    <input type="hidden" class="product-title-{{ product.id }}" value="{{ product.title }}">
                                    <button ><i class="fa fa-heart"></i></button>
                                    <button type="submit" class="add add-to-cart-btn" data-index="{{ product.id }}" id="add-to-cart-btn" style="border: none;"><i class="fa fa-shopping-cart"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}  
                

                



            </div>
        </div>
    </div>
{% endblock %}

ecomak/templates/core/product-list.html
{% extends "partials/base.html" %}
{% load static %}

{% block content %}
    <div class="filter">
        <div class="filter-m">
            <div class="by-category">
                <h4>By Category</h4>
                <div>

                    {% for c in categories %}
                    <input type="checkbox" name="checkbox" class="filter-checkbox" data-filter="category" id="" value="{{c.id}}">
                    <label for="a"><div>{{ c.title }}</div></label> <br>
                        
                    {% endfor %}
                    
                </div>
            </div>
            <div class="by-vendor">
                <h4>By Vendor</h4>
                <div>
                    <form action=".">
                        {% for v in vendors %}
                            
                            <input type="checkbox" class="filter-checkbox" data-filter="vendor" value="{{c.id}}">
                            <label for="a">{{ v.title }}</label> <br>
                        {% endfor %}
                        
                        
                        
                    </form>
                </div>
            </div>


            <div class="by-tag">
                <h4>By Tag</h4>
                <div>
                    <div><span>X</span> milk</div>
                    <div><span>X</span> salad</div>
                </div>

            </div>
            <div class="by-price">
                <h4 >By Price</h4>
                <input type="text" id="test">

                <div>
                    
                        <input type="range" id="range" value="{{ min_max_price.price__min|floatformat:2 }}"  class="slider-range"  min="{{ min_max_price.price__min|floatformat:2 }}" max="{{ min_max_price.price__max|floatformat:2 }}" oninput="max_price.value=this.value">
                        <div><span>From: {{ min_max_price.price__min }}</span> <span>To:{{ min_max_price.price__max|floatformat:2 }}</span></div>
                        <input type="number" name="" value="{{ min_max_price.price__min|floatformat:2 }}"  id="max_price" min="{{ min_max_price.price__min|floatformat:2 }}" max="{{ min_max_price.price__max|floatformat:2 }}" placeholder="Current Price" onkeyup="range.value=this.value">
                        
                        <button  id="price-filter-btn" type="button">filter</button>
                        <!-- <input type="checkbox">
                        <label for="a">netlify</label> <br>
                        
                        <input type="checkbox">
                        <label for="a">unilever</label> <br>
                       
                        <input type="checkbox">
                        <label for="a">a</label> <br>

                        <input type="checkbox">
                        <label for="a">a</label> <br>
                        <input type="checkbox">
                        <label for="a">a</label> <br> -->


                    
                </div>
            </div>
        </div>
    </div>
    <div class="prod-info">
        <p>We found 29 items for you </p>
        <div>
            <div>Show</div>
            <div>sort by</div>
        </div>
    </div>

    <div class="prod-list">
        <div class="card" id="filtered-product">
            {% for product in products %}
                <div class="product-card">
                    <div class="badge">-{{ product.get_percentage|floatformat }} <span> </span>%</div>
                    <div class="product-tumb">
                        <img src="{{ product.image.url }}" alt="{{ product.title }}">
                    </div>
                    <div class="product-details">
                        <span class="product-catagory">{{ product.Category }} </span>
                        <h4><a href="{% url 'core:product_detail' product.pid %}">{{ product.title }}</a></h4>
                        <p>{{ product.description }}</p>
                        <p>by {{ product.vendor.title }}</p>
                        <div class="product-bottom-details">
                            <div class="product-price"><small>{{ product.old_price }}</small>${{ product.price }}</div>
                            <div class="product-links">
                                <a href=""><i class="fa fa-heart"></i> </a>
                                
                                <a href=""><i class="fa fa-shopping-cart"></i>cart</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %} 

            {% for product in products %}
                <div class="product-card">
                    <div class="badge">-{{ product.get_percentage|floatformat }} <span> </span>%</div>
                    <div class="product-tumb">
                        <img src="{{ product.image.url }}" alt="{{ product.title }}">
                    </div>
                    <div class="product-details">
                        <span class="product-catagory">{{ product.Category }} </span>
                        <h4><a >{{ product.title }} </a></h4>
                        <p>{{ product.description }}</p>
                        <p>by {{ product.vendor.title }}</p>
                        <div class="product-bottom-details">
                            <div class="product-price"><small>{{ product.old_price }}</small>${{ product.price }}</div>
                            <div class="product-links">
                                <a href=""><i class="fa fa-heart"></i></a>
                                <a href=""><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}  
            {% for product in products %}
                <div class="product-card">
                    <div class="badge">-{{ product.get_percentage|floatformat }} <span> </span>%</div>
                    <div class="product-tumb">
                        <img src="{{ product.image.url }}" alt="{{ product.title }}">
                    </div>
                    <div class="product-details">
                        <span class="product-catagory">{{ product.Category }} </span>
                        <h4><a href="">{{ product.title }}</a></h4>
                        <p>{{ product.description }}</p>
                        <p>by {{ product.vendor.title }}</p>
                        <div class="product-bottom-details">
                            <div class="product-price"><small>{{ product.old_price }}</small>${{ product.price }}</div>
                            <div class="product-links">
                                <a href=""><i class="fa fa-heart"></i></a>
                                <a href=""><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %} 
            {% for product in products %}
                <div class="product-card">
                    <div class="badge">-{{ product.get_percentage|floatformat }} <span> </span>%</div>
                    <div class="product-tumb">
                        <img src="{{ product.image.url }}" alt="{{ product.title }}">
                    </div>
                    <div class="product-details">
                        <span class="product-catagory">{{ product.Category }} </span>
                        <h4><a href="">{{ product.title }}</a></h4>
                        <p>{{ product.description }}</p>
                        <p>by {{ product.vendor.title }}</p>
                        <div class="product-bottom-details">
                            <div class="product-price"><small>{{ product.old_price }}</small>${{ product.price }}</div>
                            <div class="product-links">
                                <a href=""><i class="fa fa-heart"></i></a>
                                <a href=""><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %} 
            {% for product in products %}
                <div class="product-card">
                    <div class="badge">-{{ product.get_percentage|floatformat }} <span> </span>%</div>
                    <div class="product-tumb">
                        <img src="{{ product.image.url }}" alt="{{ product.title }}">
                    </div>
                    <div class="product-details">
                        <span class="product-catagory">{{ product.Category }} </span>
                        <h4><a href="">{{ product.title }}</a></h4>
                        <p>{{ product.description }}</p>
                        <p>by {{ product.vendor.title }}</p>
                        <div class="product-bottom-details">
                            <div class="product-price"><small>{{ product.old_price }}</small>${{ product.price }}</div>
                            <div class="product-links">
                                <a href=""><i class="fa fa-heart"></i></a>
                                <a href=""><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %} 
            {% for product in products %}
                <div class="product-card">
                    <div class="badge">-{{ product.get_percentage|floatformat }} <span> </span>%</div>
                    <div class="product-tumb">
                        <img src="{{ product.image.url }}" alt="{{ product.title }}">
                    </div>
                    <div class="product-details">
                        <span class="product-catagory">{{ product.Category }} </span>
                        <h4><a href="">{{ product.title }}</a></h4>
                        <p>{{ product.description }}</p>
                        <p>by {{ product.vendor.title }}</p>
                        <div class="product-bottom-details">
                            <div class="product-price"><small>{{ product.old_price }}</small>${{ product.price }}</div>
                            <div class="product-links">
                                <a href=""><i class="fa fa-heart"></i></a>
                                <a href=""><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %} 

            
            



        </div>
    </div>

    <div class="pagination">
        <ul> <!--pages or li are comes from javascript --> </ul>
      </div>
      
{% endblock %}

ecomak/templates/core/search.html
{% extends "partials/base.html" %}
{% load static %}

{% block content %}
        {% if query %}
            <h1> {{query}} </h1>
        {% else %}
        <h1> no Searched Item </h1>
        {% endif %}

       {% for product in products %}
            {{product.title}}
        {% endfor %}

{% endblock %}

ecomak/templates/core/vendor_list.html
{% extends "partials/base.html" %}
{% load static %}

{% block content %}
        <div class="vendor_list">
        

        <div class="filter">
            <div><h4>We found 29 item for you</h4></div>
            <div>
                <div class="show">
                    <div>Show 50 </div>
                    <div class="on-hover">
                        <ul>
                            <li>1</li>
                            <li>2</li>
                            <li>3</li>
                            <li>4</li>
                        </ul>
                    </div>
                </div>
                <div class="show">
                    <div>Short by:feature</div>
                    <div class="on-hover">
                        <ul>
                            <li>1</li>
                            <li>2</li>
                            <li>3</li>
                            <li>4</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="vendors">
            <div class="vcards">
                
                {% for vendor in vendors %}
                  

                    <div class="vcard">
                        <div class="vimg">
                            <img src="{{ vendor.cover_image.url }}"  alt="">
                            <span>{{ vendor.product.all.count }}</span>
                        </div>
                        <div class="vdetails">
                            <p class="vdate">Since {{ vendor.date|date:"Y"}}</p>
                            <h4><a href="/vendor/{{vendor.vid}}">{{ vendor.title }}</a></h4>
                            vendor_detials
                            <div class="vrating">★★★☆☆</div>

                            <div>
                                <p class="vaddress">{{vendor.address}}</p>
                                <p class="vcontact">Call {{ vendor.contact }}</p>
                            </div>
                        
                        </div>
                    </div>
                {% endfor %}

               
            </div>

            
        </div>


        </div>
{% endblock %}